"""Produce the committed sample-run artifacts from a deterministic offline replay.

    cd server && python scripts/generate_sample_run.py

Writes docs/sample-run/{report.json, report.xlsx, trace.jsonl, README.md}. Uses the
EvalProvider (no network, no keys) so the artifacts are reproducible byte-for-byte
modulo timestamps. For a live-data sample, ingest a real day via POST /datasets with
keys set, run the replay from the UI, then export from the Observability tab.
"""
import json
import os
import tempfile
from pathlib import Path

os.environ["DATABASE_URL"] = f"sqlite:///{tempfile.mktemp(suffix='.sqlite')}"
os.environ["LLM_MODE"] = "cassette"

from app.db import SessionLocal, init_db  # noqa: E402
from app.models.span import Span  # noqa: E402
from app.reports.excel import report_to_xlsx  # noqa: E402
from app.agents.reporting import deterministic_summary  # noqa: E402

from eval.harness import _full_run  # noqa: E402

OUT = Path(__file__).resolve().parents[2] / "docs" / "sample-run"


def main() -> None:
    init_db()
    full = _full_run()
    run_id, report = full["run_id"], full["report"]
    report["narrative"] = deterministic_summary(report).model_dump()

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "report.json").write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
    (OUT / "report.xlsx").write_bytes(report_to_xlsx(report, report["narrative"]))

    with SessionLocal() as s:
        spans = s.query(Span).filter(Span.run_id == run_id).order_by(Span.started_at.asc()).all()
        trace = "\n".join(json.dumps(sp.as_event(), default=str) for sp in spans)
    (OUT / "trace.jsonl").write_text(trace, encoding="utf-8")

    (OUT / "README.md").write_text(
        "# Sample run\n\n"
        f"Deterministic offline replay of `{report['replay_date']}` (NVDA), generated by "
        "`server/scripts/generate_sample_run.py` with the EvalProvider — no network, no keys.\n\n"
        "- `report.json` — end-of-day report (positions, P&L vs SPY, decision log w/ citations)\n"
        "- `report.xlsx` — the same report as the second (Excel) channel\n"
        "- `trace.jsonl` — the full span trace, one event per line (replayable / auditable)\n\n"
        f"Spans: {len(spans)} · Filled trades: {report['metrics']['n_trades']} · "
        f"Portfolio return: {report['metrics']['portfolio_return'] * 100:+.2f}% vs "
        f"{report['metrics']['benchmark']} {(report['metrics']['benchmark_return'] or 0) * 100:+.2f}%\n",
        encoding="utf-8",
    )
    print(f"wrote sample run ({len(spans)} spans) to {OUT}")


if __name__ == "__main__":
    main()
